### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by akiyamaSM**
Following the PR #84

### CODE REVIEW

**Comment by bzbislawski** [comment]
This commit should be in #84 pull request, no need to create separate PR.

**Comment by akiyamaSM** [comment]
@bzbislawski I'm new to the platforme, I only use the direct editor. could you show me how?

**Comment by alaouy** [comment]
@akiyamaSM You can make the commit directly to the same branch of your first PR `patch-1`, once you push it will appear there ;)

**Comment by akiyamaSM** [comment]
@alaouy I'll make the change now ;)

**Comment by alaouy** [comment]
We can close this one.

**Pull request closed without merging**
