### PR TITLE
Added getRelatedVideos feature

### PR DESCRIPTION
**Pull request by w0rldart**

### CODE REVIEW

**Comment by alaouy** [comment]
Thank you @w0rldart for your contribution much appreciated :+1:

**Comment by w0rldart** [comment]
Happy to help. If you use Sublime Text or PHP Storm, they both have extensions to help keep PSR standard in place. Saves time.

**Comment by w0rldart** [comment]
Btw, can you please push the v1.2 tag, just so everything stays up to date (:

**Comment by w0rldart** [comment]
I am asking, because it's still pulling the `317937241aede3932f8e1517d48ddd3976c85b2b` commit. Regardless that I have `"alaouy/youtube": "dev-master",` and not specific version :\

**Comment by alaouy** [comment]
@w0rldart I just pushed to ``` v1.2 ```, you can change your composer file accordingly, Thank you again :smile:

**Pull request merged**
