### PR TITLE
remove invideoPromotion

### PR DESCRIPTION
**Pull request by stickpro**
Youtube api does not accept $part invideoPromotion

### CODE REVIEW

**Comment by ibrunotome** [comment]
Hello @alaouy I can confirm that this solves a new exception `'invideo_promotion' : unexpectedPart`.

**Comment by martinikat** [comment]
I used this solution but the problem persists

**Comment by martinikat** [comment]
Okey, i have solves. 
1 more file using invideo_promotion. 

App/Overrides/Youtube.php

**Review by alaouy — APPROVED** [review]

**Comment by alaouy** [comment]
Thank you guys 💯

**Comment by alaouy** [comment]
A new tag was release with this fix: [v2.2.4](https://github.com/alaouy/Youtube/releases/tag/v2.2.4)

**Pull request merged**
