### PR TITLE
Properly capitalize 'YouTube'

### PR DESCRIPTION
**Pull request by svenluijten**
YouTube's [brand guidelines](https://www.youtube.com/yt/about/brand-resources/#logos-icons-colors) specify that their name is spelled "YouTube", not "Youtube".

screenshot

### CODE REVIEW

**Comment by svenluijten** [comment]
**Note:** This will probably need a major version bump as the names of the classes have changed as well. Let me know how you feel about that 🙂

**Comment by bzbislawski** [comment]
You probably want to keep both facades, so that way there is no need to update code repo with all Youtube facades calls.

**Comment by svenluijten** [comment]
@bzbislawski that is why it will need a major version bump (this'd become 3.0). 🙂

**Comment by wast** [comment]
Just do it :)

**Pull request closed without merging**
